# This workflow will build a Java project with Gradle

name: ğŸ—ï¸ Build

on:
  schedule:
    - cron: '40 5 * * SAT'
  push:
    branches: [ master ]
    tags-ignore:
      - 'v*'

jobs:
  build:
    name: ğŸ—ï¸ Build and Test
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ steps.version.outputs.next-version }}
    steps:
      - name: Build trigger event ğŸ”
        run: |
          echo "event name - ${{github.event_name}}"
          echo "github.ref - ${{github.ref}}"

      - name: Checkout repository âš™ï¸
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Java âš™ï¸
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle dependencies cache âš™ï¸
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Setup Gradle wrapper cache âš™ï¸
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Validate Gradle wrapper âš™ï¸
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Grant execute permission for gradlew âš™ï¸
        run: chmod +x gradlew

      - name: Build and test ğŸ—ï¸
        run: ./gradlew clean build jacocoTestReport javadoc

      - name: Get version number ğŸ”¢
        id: get-version
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store next version ğŸ”¢
        id: version
        run: |
          echo "next-version=${{ steps.get-version.outputs.tag_name }}" | cut -c -13,15- >> $GITHUB_OUTPUT

      - name: Print next version ğŸ”¢
        run: |
          echo "Next version: ${{ steps.version.outputs.next-version }}"

  code-analysis:
    name: ğŸ” Code Analysis
    needs: [build]
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' && github.event_name != 'schedule' && github.repository == 'w3stling/rssreader' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository âš™ï¸
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Java âš™ï¸
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Cache SonarCloud packages âš™ï¸
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Setup Gradle dependencies cache âš™ï¸
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Setup Gradle wrapper cache âš™ï¸
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Validate Gradle wrapper âš™ï¸
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Grant execute permission for gradlew âš™ï¸
        run: chmod +x gradlew

      - name: Next version ğŸ”¢
        run: |
          echo "Next version: ${{ needs.build.outputs.next-version }}"

      - name: Analyze code ğŸ”ï¸
        run: ./gradlew test jacocoTestReport sonar --info -Dsonar.projectVersion=${{ needs.build.outputs.next-version }}-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  documentation:
    name: ğŸ“š Publish Javadoc
    needs: [build]
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' && github.event_name != 'schedule' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository âš™ï¸
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Java âš™ï¸
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle dependencies cache âš™ï¸
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Setup Gradle wrapper cache âš™ï¸
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Validate Gradle wrapper âš™ï¸
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Grant execute permission for gradlew âš™ï¸
        run: chmod +x gradlew

      - name: Next version ğŸ”¢
        run: |
          echo "Next version: ${{ needs.build.outputs.next-version }}"

      - name: Generate Javadoc ğŸ“
        run: ./gradlew javadoc

      - name: Deploy Javadoc ğŸ“š
        uses: JamesIves/github-pages-deploy-action@4a3abc783e1a24aeb44c16e869ad83caf6b4cc23 # v4.7.4
        with:
          branch: gh-pages
          folder: build/docs/javadoc
          target-folder: javadoc/${{ needs.build.outputs.next-version }}-SNAPSHOT
          commit-message: Publishing javadoc
          clean: true
          dry-run: false


  publish-snapshot:
    name: ğŸš€ Publish Snapshot
    needs: [build]
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' && github.event_name != 'schedule' && github.repository == 'w3stling/rssreader' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository âš™ï¸
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Java âš™ï¸
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle dependencies cache âš™ï¸
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Setup Gradle wrapper cache âš™ï¸
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Validate Gradle wrapper âš™ï¸
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Grant execute permission for gradlew âš™ï¸
        run: chmod +x gradlew

      - name: Next version ğŸ”¢
        run: |
          echo "Next version: ${{ needs.build.outputs.next-version }}"

      - name: Publish snapshot build ğŸš€
        env:
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
        run: ./gradlew publishToSonatype -Pversion=${{ needs.build.outputs.next-version }}-SNAPSHOT